"""Step 40. Verification against the published results. Three checks, each printed with a PASS or FAIL line:

  1. Result tables   every CSV in <outputs>/tables is compared numerically with the frozen copy in reference/tables
                     (the tables of the reported run). Text columns must match exactly; numbers within --tol
                     (default 1e-9: a rerun on the shipped predictions reproduces them exactly). After a full refit
                     from raw data, run with a looser tolerance and read the per table maximum differences.
  2. Paper tables    every table regenerated by step 31 (<outputs>/paper_tables) is compared cell by cell with the
                     table as printed in the manuscript and Supporting Information (reference/paper_tables).
  3. Quoted numbers  every number listed in reference/paper_numbers.csv (268 numbers quoted in the abstract and
                     the text, with their location) is recomputed from <outputs>/tables, formatted as printed and
                     compared with the printed value.
  If <outputs> is not the repository's own outputs/ directory (CSP_OUTPUTS set, for example after a refit), the
  window level predictions are also compared with the shipped ones (maximum absolute difference of the probability).

Usage: python pipeline/40_verify.py [--tol 1e-9] [--skip-tables]
Exit status 0 when every check passes."""
import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))
import argparse, csv
from decimal import Decimal, ROUND_HALF_UP
import numpy as np, pandas as pd

from csp.paths import ROOT, OUTPUTS, TABLES, PAPER, PRED, REFERENCE

ap = argparse.ArgumentParser(); ap.add_argument("--tol", type=float, default=1e-9)
ap.add_argument("--skip-tables", action="store_true"); args = ap.parse_args()
failures = []


def report(ok, what):
    print(("PASS  " if ok else "FAIL  ") + what)
    if not ok: failures.append(what)


# ------------------------------------------------------------------ 1. result tables
if not args.skip_tables:
    print("\n== 1. result tables against reference/tables")
    for ref in sorted((REFERENCE / "tables").glob("*.csv")):
        new = TABLES / ref.name
        if not new.exists():
            report(False, f"{ref.name}: missing in {TABLES}"); continue
        a, b = pd.read_csv(new), pd.read_csv(ref)
        if list(a.columns) != list(b.columns) or a.shape != b.shape:
            report(False, f"{ref.name}: shape or columns differ {a.shape} vs {b.shape}"); continue
        num = [c for c in b.columns if pd.api.types.is_numeric_dtype(b[c])]
        txt = [c for c in b.columns if c not in num]
        t_ok = all((a[c].astype(str) == b[c].astype(str)).all() for c in txt)
        if num:
            A, B = a[num].values.astype(float), b[num].values.astype(float)
            nan_ok = (np.isnan(A) == np.isnan(B)).all()
            d = np.nanmax(np.abs(A - B)) if np.isfinite(B).any() else 0.0
        else:
            nan_ok, d = True, 0.0
        report(t_ok and nan_ok and d <= args.tol, f"{ref.name:40s} max abs difference {d:.2e}"
               + ("" if t_ok else "  (text columns differ)") + ("" if nan_ok else "  (missing values differ)"))

# ------------------------------------------------------------------ predictions (only for a separate run)
if OUTPUTS != (ROOT / "outputs").resolve():
    print("\n== predictions of this run against the shipped predictions")
    shipped = ROOT / "outputs" / "predictions"
    for f in sorted(PRED.rglob("*.csv")):
        g = shipped / f.relative_to(PRED)
        if not g.exists(): continue
        a, b = pd.read_csv(f), pd.read_csv(g)
        if len(a) != len(b):
            print(f"      {f.relative_to(PRED)}: row counts differ"); continue
        d = np.abs(a.proba.values - b.proba.values).max()
        print(f"      {str(f.relative_to(PRED)):40s} max |Δ proba| {d:.2e}")

# ------------------------------------------------------------------ 2. paper tables
print("\n== 2. regenerated paper tables against the printed tables (reference/paper_tables)")


def norm(s): return " ".join(str(s).replace("−", "-").replace("−", "-").split())


for ref in sorted((REFERENCE / "paper_tables").glob("Table_*.csv")):
    new = PAPER / ref.name
    if not new.exists():
        report(False, f"{ref.name}: not generated (run step 31)"); continue
    printed = list(csv.reader(open(ref, encoding="utf-8")))
    gen = list(csv.reader(open(new, encoding="utf-8")))[1:]
    bad = []
    if len(printed) != len(gen):
        bad.append(f"{len(gen)} rows generated, {len(printed)} printed")
    for i, (p, g) in enumerate(zip(printed, gen)):
        cells = range(1, len(p)) if ref.stem == "Table_II" else range(len(p))   # Table II: labels are text
        for j in cells:
            if j >= len(g) or norm(p[j]) != norm(g[j]):
                bad.append(f"row {i + 1} col {j + 1}: printed '{p[j]}' regenerated '{g[j] if j < len(g) else ''}'")
    report(not bad, f"{ref.stem:12s} {len(printed)} rows" + ("" if not bad else ": " + "; ".join(bad[:5])))

# ------------------------------------------------------------------ 3. numbers quoted in the text
print("\n== 3. numbers quoted in the text (reference/paper_numbers.csv)")
DET = ["RF", "GB", "RF+GB", "LR", "MLP"]; ORDER = DET + ["Clock"]; NEG = ["Clock", "RF time only", "GB time only"]


def T(n, idx="model"):
    t = pd.read_csv(TABLES / f"{n}.csv"); return t.set_index(idx) if idx else t


def f0(x): return f"{int(Decimal(str(x)).quantize(Decimal('1'), ROUND_HALF_UP)):,}" if x >= 1000 else \
    str(int(Decimal(str(x)).quantize(Decimal("1"), ROUND_HALF_UP)))
def f1(x): return f"{x:.1f}"
def f2(x): return f"{x:.2f}"
def f3(x): return f"{x:.3f}"
def sg(x): return ("+" if x >= 0 else "−") + f"{abs(x):.3f}"
def iv(lo, hi): return f"[{lo:.3f}, {hi:.3f}]".replace("-", "−")
def cnt(x): return f"{int(round(x)):,}"
def pct(x):
    q = Decimal(str(round(100 * x, 6))).quantize(Decimal("0.1") if 0 < x < 0.1 else Decimal("1"), ROUND_HALF_UP)
    return f"{q}%"


NS = dict(DET=DET, ORDER=ORDER, NEG=NEG, f0=f0, f1=f1, f2=f2, f3=f3, sg=sg, iv=iv, cnt=cnt, pct=pct, np=np, pd=pd,
          PR=T("T_primary"), S8=T("T_primary_stats"), LA=T("T_lpgo_atime"), AS=T("T_asev_paired"),
          SV=T("T_severity"), OR=T("T_original99"), LO=T("T_loro"), ME=T("T_merged"), EP=T("T_episodes"),
          NW=T("T_nested_w"), NWC=T("T_nested_w_choices", None), SWP=T("T_smoothing_paired_vs_clock", None),
          SEC=T("T_secondary_tests", None), SUPS=T("T_sup_seeds", None), DP=T("T_deploy", None),
          PSH=T("T_prior_shift", None), S3B=T("T_s3_by_group", None), S3G=T("T_s3_without_big_group", None),
          K=T("T_constants", "name").value, DF=T("T_dataset_facts", "name").value, AF=T("T_archive_facts", "name").value)
CT = T("T_controls", None); CT = CT[CT.learner == "LR"]; NS["CT"] = CT
LK = T("T_leakage", None); SW = T("T_smoothing", None); ASG = T("T_asev_by_group", None); LGT = T("T_loro_by_grouptype", None)
NS.update(
    LKL=T("T_leakage_loro", None).iloc[0],
    lk=lambda split: LK[LK.split == split].iloc[0],
    ct=lambda kind, delta: CT[(CT.kind == kind) & ((CT.delta - delta).abs() < 1e-9)].iloc[0],
    sw=lambda m, w: SW[(SW.model == m) & (SW.w == w)].mcc.iloc[0],
    lg=lambda m, design: LGT[(LGT.model == m) & (LGT.design == design) & (LGT.subset == "multi")].mcc.iloc[0],
    asg=lambda m, g: ASG[(ASG.model == m) & (ASG.group == g)].a_sev.iloc[0],
    asg_pairs=lambda g=None: ASG[(ASG.model == "Clock") & ((ASG.group == g) if g is not None else True)].pairs.sum())
RAWC = T("CTRL_LR", None); RAWC = RAWC[RAWC.learner == "LR"]
ERR = T("T_episode_random_reference", None); AB = T("T_ablation", None)
NS.update(err=lambda m, tgt: ERR[(ERR.model == m) & (ERR.target.isna() if tgt is None else (ERR.target - tgt).abs() < 1e-9)].iloc[0],
          ab=lambda cfg, m: AB[(AB.config == cfg) & (AB.model == m)].mcc.iloc[0])
NS.update(band=lambda: RAWC[(RAWC.kind == "trait") & RAWC.dl.between(0.10, 0.15)],     # realized improvement near the RF's
          tnull=lambda: RAWC[(RAWC.kind == "trait") & (RAWC.delta == 0)])
ok_n, bad_n = 0, []
for r in csv.DictReader(open(REFERENCE / "paper_numbers.csv", encoding="utf-8")):
    try:
        got = str(eval(r["expr"], NS))
    except Exception as e:                                    # noqa: BLE001
        got = f"error: {e}"
    if norm(got) == norm(r["printed"]): ok_n += 1
    else: bad_n.append(f"{r['id']} {r['location']}: printed {r['printed']}, recomputed {got}")
for b in bad_n: print("      " + b)
report(not bad_n, f"{ok_n} of {ok_n + len(bad_n)} quoted numbers reproduced")

print("\n" + ("ALL CHECKS PASSED" if not failures else f"{len(failures)} CHECK(S) FAILED"))
sys.exit(0 if not failures else 1)
